### ISSUE TITLE
Handling html escaped characters in results view

### ISSUE THREAD

**Issue by benabel** [h5p/h5p-flashcards#52]
It seems that escaped characters are not correctly rendered in the results page.

![Screenshot_20200605_152050](https://user-images.githubusercontent.com/12530561/83881470-0366c100-a741-11ea-94da-77393502cfcb.png)

**Comment by otacke** [comment]
And there's a [fix waiting to be merged](https://github.com/h5p/h5p-flashcards/pull/50) in ...

**Comment by benabel** [comment]
OK I didn't look at prs before submitting the issue. 

So far I.ve seen that you have proposed another prs but never received an answer. I don't really understand  how the h5p team use Github as they also use atlassian.

**Comment by otacke** [comment]
@benabel github is for managing and distributing code, JIRA is for managing and keeping track of issues and progress. There's an overlap for sure, but both serve different purposes. And yes, I assume some pull-requests may be overlooked if there's no issue created for them on JIRA.

**Comment by benabel** [comment]
Thanks for your response @otacke.
So I close this issue because github isn't used for issues.
